<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9"
  exclude-result-prefixes="s">
  <xsl:output method="html" encoding="UTF-8" indent="yes" doctype-system="about:legacy-compat"/>
  <xsl:template match="/">
    <html lang="zh-CN">
      <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>站点地图 · XML Sitemap</title>
        <style>
          :root { --brand:#185FA5; --ink:#1f2933; --muted:#6b7280; --line:#e5e7eb; --bg:#f7f9fc; }
          * { box-sizing: border-box; }
          body { margin:0; font-family:-apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif; color:var(--ink); background:var(--bg); }
          header { background:var(--brand); color:#fff; padding:28px 20px; }
          header .wrap { max-width:960px; margin:0 auto; }
          header h1 { margin:0 0 6px; font-size:22px; }
          header p { margin:0; opacity:.85; font-size:14px; }
          main { max-width:960px; margin:24px auto; padding:0 20px; }
          .count { font-size:14px; color:var(--muted); margin-bottom:14px; }
          table { width:100%; border-collapse:collapse; background:#fff; border:1px solid var(--line); border-radius:12px; overflow:hidden; }
          th, td { text-align:left; padding:12px 14px; border-bottom:1px solid var(--line); font-size:14px; vertical-align:top; }
          th { background:#eef3fa; color:var(--brand); font-weight:600; }
          tr:last-child td { border-bottom:none; }
          td a { color:var(--brand); text-decoration:none; word-break:break-all; }
          td a:hover { text-decoration:underline; }
          .pri { font-variant-numeric:tabular-nums; color:var(--muted); }
          footer { max-width:960px; margin:20px auto 40px; padding:0 20px; color:var(--muted); font-size:12px; }
        </style>
      </head>
      <body>
        <header>
          <div class="wrap">
            <h1>站点地图 (XML Sitemap)</h1>
            <p>本文件遵循 Sitemap 0.9 协议，便于搜索引擎抓取；同时以可读表格呈现。</p>
          </div>
        </header>
        <main>
          <p class="count">共收录 <xsl:value-of select="count(s:urlset/s:url)"/> 个网址。</p>
          <table>
            <thead>
              <tr><th>网址 URL</th><th>最后更新</th><th>更新频率</th><th>优先级</th></tr>
            </thead>
            <tbody>
              <xsl:for-each select="s:urlset/s:url">
                <tr>
                  <td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
                  <td><xsl:value-of select="s:lastmod"/></td>
                  <td><xsl:value-of select="s:changefreq"/></td>
                  <td class="pri"><xsl:value-of select="s:priority"/></td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </main>
        <footer>
          Generated by 商友智能营销云软件 · 协议: http://www.sitemaps.org/schemas/sitemap/0.9
        </footer>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
